name: "QRMjoke"

description: "use an external API to retrieve and display a joke"

outputs:
  joke-output:
    description: The resulting joke from the icanhazdadjokes API

# runs:
#   using: "node12"
#   main: "main.js"

runs:
  using: "composite"
  steps:
    - run: ls
      shell: bash
    - run: npm i
      shell: bash
    - run: npm run start
      shell: bash